title: La Olla Colectivo
description: Estás en la página web del colectivo La Olla.
            Colombia & Freiburg, Alemania.
google_analytics:

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

collections:
  pages:
    output: true
    permalink: /:name/

baseurl: "/laollasite"  # Project repo name here

